AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Batch job definition.

Parameters:
  EnvironmentVariable:
    Type: String
    Description: Environment variable
  EnvironmentVariableSecure:
    Type: String
    NoEcho: true
    Description: Environment variable secure
  Image:
    Type: String
    Description: Docker image repository. See detail - https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html?shortFooter=true#cfn-batch-jobdefinition-containerproperties-image

Resources:
  AWSBatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      ContainerProperties:
        Memory: 256
        Environment:
          - Name: ENVIRONMENT_VARIABLE
            Value: !Ref EnvironmentVariable
          - Name: ENVIRONMENT_VARIABLE_SECURE
            Value: !Ref EnvironmentVariableSecure
        Vcpus: 1
        Image: !Ref Image
